### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by corelon** [searchbox-io/Jest#109]
I setup the Client setting multiThreaded(false) in the HttpClientConfig.
I have a Bulk action containing a list of Index requests.
When I try to run execute() I get a ConcurrentModificationException.
Am I doing something wrong or is this a bug?
This happens regardless of the multiThreaded setting (true or false).
I am using version 0.0.6 (still on 0.90.2) and the stack trace that appears constantly is :
```
java.util.ConcurrentModificationException
        at java.util.SubList.checkForComodification(AbstractList.java:752)
        at java.util.SubList.listIterator(AbstractList.java:682)
        at java.util.AbstractList.listIterator(AbstractList.java:284)
        at java.util.SubList.iterator(AbstractList.java:678)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:95)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:60)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145)
        at com.google.gson.Gson.toJson(Gson.java:593)
        at com.google.gson.Gson.toJson(Gson.java:572)
        at com.google.gson.Gson.toJson(Gson.java:527)
        at com.google.gson.Gson.toJson(Gson.java:507)
        at io.searchbox.core.Bulk.getJson(Bulk.java:45)
        at io.searchbox.core.Bulk.getData(Bulk.java:102)
        at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:54)
```

**Comment by kramer** [comment]
Closing this issue as no update was made in a long time. Please feel free to reopen if you come up with any new information.
