### ISSUE TITLE
Null pointer exception when getting hits from search result

### ISSUE THREAD

**Issue by imod** [searchbox-io/Jest#119]
From time to time we face a `NullPointerException` when accessing the hits...

```
May 05 22:19:00 yooture-admin1 i-f8032eb7: 06-May-2014 05:18:59.918 SEVERE [http-bio-8782-exec-9] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [admin] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
May 05 22:19:00 yooture-admin1 i-f8032eb7:  java.lang.NullPointerException
May 05 22:19:00 yooture-admin1 i-f8032eb7: at io.searchbox.core.SearchResult.getHits(SearchResult.java:66)
May 05 22:19:00 yooture-admin1 i-f8032eb7: at io.searchbox.core.SearchResult.getHits(SearchResult.java:54) 
```

I know this is not a lot of information about the issue, but I think it is fair to say that in the following extract of SearchResult.java:66 :

```
                JsonElement obj = jsonObject.get(keys[0]);
                for (int i = 1; i < keys.length - 1; i++) {
                    obj = ((JsonObject) obj).get(keys[i]);
                }
```

`obj`might well be null.

**Comment by xiaohundun** [comment]
I have the same problem, but sometimes it’s good, sometimes not, don't know how to reproduce
