### ISSUE TITLE
Problem with org.apache.http.conn.ConnectTimeoutException

### ISSUE THREAD

**Issue by lewismc** [searchbox-io/Jest#266]
Hi Folks,
I am using Jest 2.0.0 within my application. The code can be seen in the [following patch](https://github.com/lewismc/memex_es/blob/master/memex_cdr_plugin.patch) particularly within the [following lines](https://github.com/lewismc/memex_es/blob/master/memex_cdr_plugin.patch#L1228-L1412).
When I run the code I get the following stack trace which is causing me trouble to debug the connection timeout.
I wonder if anyone can have a look over the code and tell me if there looks to be anything I am doing wrong? Additionally, does anyone have an idea about what the ConnectTimeoutException may be caused by?
Thank you
Lewis
```
java.lang.Exception: org.apache.http.conn.ConnectTimeoutException: Connect to 172.XX.XX.XX:XXXXX[/172.XX.XX.XX] failed: Connection timed out
	at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:462)
	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:529)
Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to 172.XX.XX.XX:XXXXX[/172.XX.XX.XX] failed: Connection timed out
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:138)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:318)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:48)
	at org.apache.nutch.indexwriter.memex.MemexIndexWriter.write(MemexIndexWriter.java:110)
	at org.apache.nutch.indexer.IndexWriters.write(IndexWriters.java:85)
	at org.apache.nutch.indexer.IndexerOutputFormat$1.write(IndexerOutputFormat.java:50)
	at org.apache.nutch.indexer.IndexerOutputFormat$1.write(IndexerOutputFormat.java:41)
	at org.apache.hadoop.mapred.ReduceTask$OldTrackingRecordWriter.write(ReduceTask.java:493)
	at org.apache.hadoop.mapred.ReduceTask$3.collect(ReduceTask.java:422)
	at org.apache.nutch.indexer.IndexerMapReduce.reduce(IndexerMapReduce.java:356)
	at org.apache.nutch.indexer.IndexerMapReduce.reduce(IndexerMapReduce.java:56)
	at org.apache.hadoop.mapred.ReduceTask.runOldReducer(ReduceTask.java:444)
	at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:392)
	at org.apache.hadoop.mapred.LocalJobRunner$Job$ReduceTaskRunnable.run(LocalJobRunner.java:319)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:72)
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:123)
	... 26 more
2015-11-24 00:27:35,397 ERROR indexer.IndexingJob - Indexer: java.io.IOException: Job failed!
	at org.apache.hadoop.mapred.JobClient.runJob(JobClient.java:836)
	at org.apache.nutch.indexer.IndexingJob.index(IndexingJob.java:145)
	at org.apache.nutch.indexer.IndexingJob.run(IndexingJob.java:223)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.nutch.indexer.IndexingJob.main(IndexingJob.java:232)
```

**Comment by kramer** [comment]
Looks like a regular connection error to me. I don't see anything particular in your code that can cause this and in fact you are setting the timeout to 30 seconds...

Are you getting this error as soon as you run the code or after some successful connections? If it's the latter I would suspect no free connections in the pool, if it's the former than I can only recommend [checking things in the connection level](http://stackoverflow.com/a/86908/135503) (i.e.: confirm that the host machine has access to that IP and port, any firewall on the host is configured properly to allow your app on that port etc.).

**Comment by lewismc** [comment]
Hi @kramer thank you for response I really appreciate it. OK so here is some more logging output and it appears that some bulk operations are successful...
```
2015-11-24 00:51:15,044 WARN  conf.Configuration - file:/mnt1/var/lib/hadoop/hadoop_tmp/mapred/local/localRunner/hadoop/job_local1036620050_0001/job_local1036620050_0001.xml:an attempt to override final parameter: mapreduce.job.end-notification.max.attempts;  Ignoring.
2015-11-24 00:55:28,337 INFO  indexer.IndexWriters - Adding org.apache.nutch.indexwriter.memex.MemexIndexWriter
2015-11-24 00:55:28,682 DEBUG client.AbstractJestClient - Server pool was updated to contain 1 servers.
2015-11-24 00:55:28,684 INFO  client.JestClientFactory - Using multi thread/connection supporting pooling connection manager
2015-11-24 00:55:28,850 INFO  client.JestClientFactory - Using default GSON instance
2015-11-24 00:55:28,850 INFO  client.JestClientFactory - Node Discovery enabled...
2015-11-24 00:55:28,890 INFO  client.JestClientFactory - Idle connection reaping disabled...
2015-11-24 00:55:28,975 DEBUG http.JestHttpClient - GET method created based on client request
2015-11-24 00:55:28,975 DEBUG http.JestHttpClient - Request method=GET url=https://xxx.ixxxxxxx.com:xxxxx/_nodes/_all/http
2015-11-24 00:55:29,212 INFO  memex.MemexIndexWriter - Built and added document to index batch.
2015-11-24 00:55:29,226 INFO  memex.MemexIndexWriter - Built and added document to index batch.
2015-11-24 00:55:29,382 INFO  memex.MemexIndexWriter - Built and added document to index batch.
...
2015-11-24 00:55:29,776 INFO  memex.MemexIndexWriter - Built and added document to index batch.
2015-11-24 00:55:29,790 INFO  memex.MemexIndexWriter - Built and added document to index batch.
2015-11-24 00:55:29,825 DEBUG action.AbstractAction - Request and operation succeeded
2015-11-24 00:55:29,829 INFO  discovery.NodeChecker - Discovered 9 HTTP hosts: http://172.XX.XX.XX:19XXX,http://172.XX.XX.XX:19XXX,http://172.XX.XX.XX:19XXX,http://172.XX.XX.XX:19XXX,http://172.XX.XX.XX:19XXX,http://172.XX.XX.XX:19XXX,http://172.XX.XX.XX:19XXX,http://172.XX.XX.XX:19XXX,http://172.XX.XX.XX:19XXX
2015-11-24 00:55:29,829 DEBUG client.AbstractJestClient - Server pool was updated to contain 9 servers.
2015-11-24 00:55:29,842 INFO  memex.MemexIndexWriter - Built and added document to index batch.
2015-11-24 00:55:29,843 INFO  memex.MemexIndexWriter - Built and added document to index batch.
...
2015-11-24 00:55:31,949 INFO  memex.MemexIndexWriter - Built and added document to index batch.
2015-11-24 00:55:31,951 INFO  memex.MemexIndexWriter - Built and added document to index batch.
2015-11-24 00:55:32,792 DEBUG http.JestHttpClient - POST method created based on client request
2015-11-24 00:55:32,974 DEBUG http.JestHttpClient - Request method=POST url=http://172.XX.XX.XX:XXXXX/memex-xxxxxx-xxx/xxxxxxxxx/_bulk
2015-11-24 00:55:39,830 DEBUG http.JestHttpClient - GET method created based on client request
2015-11-24 00:55:39,830 DEBUG http.JestHttpClient - Request method=GET url=http://172.XX.XX.XX:XXXXX/_nodes/_all/http
2015-11-24 00:57:40,678 WARN  mapred.LocalJobRunner - job_local1036620050_0001
java.lang.Exception: org.apache.http.conn.ConnectTimeoutException: Connect to 172.XX.XX.XX:XXXXX [/172.XX.XX.XX] failed: Connection timed out
        at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:462)
        at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:529)
Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to 172.XX.XX.XX:XXXXX[/172.XX.XX.XX] failed: Connection timed out
        at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:138)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:318)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
```
I'll look into the stackoverflow link you've posted thank you for that.
Any ideas with the above context? 
Thanks again @kramer

**Comment by kramer** [comment]
I don't see anything particularly problematic but some general guess/advices:

* One possibility is that your bulk request is too big and overwhelming the server to the point where it cannot accept any more connections. You can try reducing the batch size (of your bulk request) to see if the problem goes away or you can even try manually calling something on one of the (active) nodes while your code is running to see if they respond to non-jest calls.
* I did not check your whole code but please make sure you are not creating the factory or the client for each request, factory can be singleton and client can be shared.

**Comment by lewismc** [comment]
hi @kramer 

> One possibility is that your bulk request is too big and overwhelming the server to the point where it cannot accept any more connections. You can try reducing the batch size (of your bulk request) to see if the problem goes away or you can even try manually calling something on one of the (active) nodes while your code is running to see if they respond to non-jest calls.

Yeah I tried 1000, then 500 and I've tried 250 and less in the bulk call... same result unfortunately.

> I did not check your whole code but please make sure you are not creating the factory or the client for each request, factory can be singleton and client can be shared.

I am double checking this and also adding code to close the client and execute a flush of all pending documents to the ES cluster. I hope that will fix the timeout. Thanks for your help. I'll report back here once I fix the issue.

**Comment by fred-github** [comment]
hi @kramer ,l have met a similar problem ,as you mentioned on the second floor ->"Are you getting this error as soon as you run the code or after some successful connections? If it's the latter I would suspect no free connections in the pool, ",i guess i get the latter,i use the regular way to get the JestClient ,but when i startup the app ,it works well,but i refresh the page after a few minutes, it tells me the error ' connection reset', how can i solve the problem ,

**Comment by lewismc** [comment]
OK I actually resolve the issue(s) here. They are as follows
 * Versioning Mismatch: I was trying to use the Jest 2.0.0 client to ingest data into ES 1.7.1. Once I downgraded to Jest 1.0.0 some of my issues went away. I was not aware that the remote ES cluster was running ES 1.7.1.
 * I had previously set node discovery to true as this would poll and
update the list of servers in the client periodically. This accounts for
the ability to ingest data into any node in the cluster. It now appears
that this setting did not redirect incoming client connections to the
correct HTTPS URL for the ES node(s) hence connections stagnated and eventually timed out.
This accounts for my consistent commentary on nodes being discovered but
timeout issues hampering ingestion of data into the ES cluster.

Thank you @kramer for your help Sir. I really appreciate it.
