### ISSUE TITLE
how to add patch to the jar file httpclinet-osgi

### ISSUE THREAD

**Issue by balubollam** [searchbox-io/Jest#268]
HI Everyone

I am implementing Jest client for Amazon client client connection.But iam getting this following error:
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/ssl/SSLContexts
    at org.apache.http.conn.ssl.SSLConnectionSocketFactory.getSocketFactory(SSLConnectionSocketFactory.java:172)
    at io.searchbox.client.config.HttpClientConfig$Builder.build(HttpClientConfig.java:247)
    at com.ktree.amazon.esclient.ConnectToAmazon.main(ConnectToAmazon.java:14)
Caused by: java.lang.ClassNotFoundException: org.apache.http.ssl.SSLContexts
  
But when i R&D on this i had come to know that 
*I need to add patch to the httpcontext-osji using dependencies i.e adding pom.xml
Can Any one Please help me out how to add this patch  or How to solve this error?

**Comment by oxymor0n** [comment]
are you sure you have Apache HttpClient in your classpath?

**Comment by arpita43** [comment]
Hi...Did it get resolved ? I am getting the below error:

Exception in thread "main" java.lang.NoClassDefFoundError: io/searchbox/action/Action
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)

Any resolution would be helpful. Thanks :)
