### ISSUE TITLE
Search Error

### ISSUE THREAD

**Issue by developersLxz** [searchbox-io/Jest#271]
I first used jest, I do not know why there is this mistake, which is what I missed yet
Thanks!

code

public static void main(String[] args) throws IOException {
		JestClientFactory factory = new JestClientFactory();
		 factory.setHttpClientConfig(new HttpClientConfig
		                        .Builder("http://localhost:9200")
		                        .build());
		 JestClient client = factory.getObject();
		
		QueryBuilder queryBuilder = QueryBuilders.matchAllQuery();
		
		SearchSourceBuilder searchSourceBuilder = new SearchSourceBuilder();
		searchSourceBuilder.query(QueryBuilders.matchAllQuery());

		
		System.out.println(searchSourceBuilder.toString());
		Search.Builder builder = new Search.Builder(searchSourceBuilder.toString());
		Search search = builder.addIndex("demo1").build();
		SearchResult result  = client.execute(search);
		System.out.println(result.getSourceAsString());
		
	}

ERROR

Exception in thread "main" com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 1 column 280 path $.hits.hits[0].title
	at com.google.gson.internal.Streams.parse(Streams.java:60)
	at com.google.gson.JsonParser.parse(JsonParser.java:84)
	at com.google.gson.JsonParser.parse(JsonParser.java:59)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at io.searchbox.action.AbstractAction.parseResponseBody(AbstractAction.java:94)
	at io.searchbox.action.AbstractAction.createNewElasticSearchResult(AbstractAction.java:65)
	at io.searchbox.core.Search.createNewElasticSearchResult(Search.java:33)
	at io.searchbox.core.Search.createNewElasticSearchResult(Search.java:1)
	at io.searchbox.client.http.JestHttpClient.deserializeResponse(JestHttpClient.java:132)
	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:49)
	at jest.Test.main(Test.java:54)
Caused by: com.google.gson.stream.MalformedJsonException: Expected ':' at line 1 column 280 path $.hits.hits[0].title
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1573)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:534)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:429)
	at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:646)
	at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:669)
	at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:661)
	at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:669)
	at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:669)
	at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:644)
	at com.google.gson.internal.Streams.parse(Streams.java:48)
	... 10 more

**Comment by happyprg** [comment]
would you please attach request query(="searchSourceBuilder.toString()") to this article.

**Comment by kramer** [comment]
It's not the request, it's the response (see `JestHttpClient.deserializeResponse(JestHttpClient.java:132)` in stack trace). Could be a proxy error, Jest/ES version mismatch, or even a node/cluster error - things you can do: verify your node accepts the same request manually (via curl etc.), debug or override the parser code to log the actual response message.

**Comment by developersLxz** [comment]
yes,my Jest/ES version mismatch , ES 1.4.2  and Jest master  .
I switched to es_1.0 version, but still there will be such a problem .

**Comment by kramer** [comment]
> but still there will be such a problem .

What exactly do you mean by that? 

If you are saying that you are still getting the same exception then there is no solution we can remotely provide you unless you find out what the actual response says.

If you are saying this exception should not be thrown in similar cases and you believe it is a bug then I'd like to remind you that Jest can only work with JSON responses which under normal circumstances ES always provides, if response is not JSON then it is an exceptional case and therefore is handled as such.

**Comment by developersLxz** [comment]
I fixed the problem, its because of Jest/ES version mismatch. thank you very much for the helps
