### ISSUE TITLE
[jest - indexing document ] Connection reset when i try to add a custom id

### ISSUE THREAD

**Issue by jhusson** [searchbox-io/Jest#294]
Hi,

I added document into my ES using jest, 
```java
JestClient client = JestClientInstance.getInstance();
		Index index = new Index.Builder(my_obj).index("my_index").type("my_type").build();
		client.execute(index);
```
but when i try to add a custom id ( same error if i use @JestId and set my field ), i got this error
```java
JestClient client = JestClientInstance.getInstance();
		Index index = new Index.Builder(my_obj).index("my_index").type("my_type").id("123456").build();
		client.execute(index);
```
```
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:196)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:48)
```

**Comment by jhusson** [comment]
I know what happened ... i customed my NGINX server to disallow PUT request.

In First case Jest do a POST, in the second a PUT.

But my question is why JEST do a PUT when a specific index ID is typed explicitly?

**Comment by kramer** [comment]
> In First case Jest do a POST, in the second a PUT.

POST is used in case of automatic ID generation as per [Elasticsearch docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html#_automatic_id_generation).
