### ISSUE TITLE
bulk insert error

### ISSUE THREAD

**Issue by jhusson** [searchbox-io/Jest#295]
Hi,

I'm not sure if it's me or jest but i got this error when i try bulk insert, i added guava but same error ...
I'm using jest 2.0
```
java.lang.ClassNotFoundException: com.google.common.reflect.TypeToken
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1714)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1559)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2895)
	at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:1173)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1681)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1559)
	at io.searchbox.core.Bulk.getData(Bulk.java:96)
	at io.searchbox.client.http.JestHttpClient.prepareRequest(JestHttpClient.java:82)
	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:47)
```

**Comment by jhusson** [comment]
I had jest-common in other pom ... sorry
