### ISSUE TITLE
SSL: Failed Certificate Verification

### ISSUE THREAD

**Issue by leviwilson** [searchbox-io/Jest#328]
## Description

If you are connecting to an ElasticSearch service that supports SSL, it successfully is able to discover the HTTP nodes in the `NodeChecker`, however any other operation fails since Jest uses the [IP address](https://github.com/searchbox-io/Jest/blob/2aaaf4acea38d765af0845631c2bf451373d555f/jest-common/src/main/java/io/searchbox/client/config/discovery/NodeChecker.java#L137) rather than the DNS name.

Here is some sample output of the failure:

```
08:26:23.347 [NodeChecker RUNNING] DEBUG i.s.client.http.JestHttpClient - GET method created based on client request
08:26:23.347 [NodeChecker RUNNING] DEBUG i.s.client.http.JestHttpClient - Request method=GET url=https://es.whatever.com:9200/_nodes/_all/http
08:26:24.091 [NodeChecker RUNNING] DEBUG io.searchbox.action.AbstractAction - Request and operation succeeded
08:26:24.092 [NodeChecker RUNNING] INFO  i.s.c.config.discovery.NodeChecker - Discovered 1 HTTP hosts: https://127.0.0.1:9200
08:26:24.092 [NodeChecker RUNNING] DEBUG i.s.client.AbstractJestClient - Server pool was updated to contain 1 servers.
08:26:55.250 [qtp149754868-47] DEBUG i.s.client.http.JestHttpClient - POST method created based on client request
08:26:55.253 [qtp149754868-47] DEBUG i.s.client.http.JestHttpClient - Request method=POST url=https://127.0.0.1:9200/_bulk
08:26:55.319 [I/O dispatcher 1] ERROR i.s.client.http.JestHttpClient - Exception occurred during async execution.
javax.net.ssl.SSLPeerUnverifiedException: Host name '127.0.0.1' does not match the certificate subject provided by the peer (CN=*.whatever.com, OU=Domain Control Validated)
    at org.apache.http.nio.conn.ssl.SSLIOSessionStrategy.verifySession(SSLIOSessionStrategy.java:208) ~[httpasyncclient-4.1.1.jar:4.1.1]
    at org.apache.http.nio.conn.ssl.SSLIOSessionStrategy$1.verify(SSLIOSessionStrategy.java:188) ~[httpasyncclient-4.1.1.jar:4.1.1]
    at org.apache.http.nio.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:366) ~[httpcore-nio-4.4.4.jar:4.4.4]
    at org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:507) ~[httpcore-nio-4.4.4.jar:4.4.4]
    at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:122) ~[httpcore-nio-4.4.4.jar:4.4.4]
    at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:164) [httpcore-nio-4.4.4.jar:4.4.4]
    at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:339) [httpcore-nio-4.4.4.jar:4.4.4]
    at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:317) [httpcore-nio-4.4.4.jar:4.4.4]
    at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:278) [httpcore-nio-4.4.4.jar:4.4.4]
    at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:106) [httpcore-nio-4.4.4.jar:4.4.4]
    at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:590) [httpcore-nio-4.4.4.jar:4.4.4]
    at java.lang.Thread.run(Thread.java:722) [na:1.7.0_15]
```

The sample code creates the `JestClient` like so:

``` java
public JestClient getClient() throws Throwable {
    final HttpClientConfig httpConfig = return new HttpClientConfig.Builder(hostName)
      .multiThreaded(true)
      .defaultSchemeForDiscoveredNodes("https")
      .discoveryEnabled(true)
      .discoveryFrequency(1L, TimeUnit.MINUTES)
      .build();

    JestClientFactory factory = new JestClientFactory();
    factory.setHttpClientConfig(httpConfig);
    return factory.getObject();
}
```
## Question

Is there any way to get Jest to use the DNS name (as mentioned in #270) of the nodes rather than the IP address? Otherwise the only way to get SSL to work would be to turn off  SSL verification (as noted [in the README](https://github.com/searchbox-io/Jest/blob/2aaaf4acea38d765af0845631c2bf451373d555f/jest/README.md#https--ssl)).

**Comment by kramer** [comment]
You can pass hostnames as the initial server list and it will work, but as you discovered only the ip addresses of the discovered nodes will be used. We can have a config option like `useHostnameForDiscoveredNodes` to use the `hostname` field in the nodes info response instead of `http_address` if that helps; otherwise my experience with SSL stuff is quite limited and I'm open to suggestions.

**Comment by leviwilson** [comment]
Oh, awesome! I wasn't aware of the `useHotnameForDiscoveredNodes`...let me check that out and I'll report back; that _may_ get me there.

**Comment by kramer** [comment]
> I wasn't aware of the useHotnameForDiscoveredNodes...

Jest doesn't have that currently, I meant to say we can *add* it :)

**Comment by leviwilson** [comment]
Ahh, sorry...sometimes words mean things :wink: Yeah, that would get me where I need to be; that's the whole problem is that the discovered nodes capture the IP only, causing the certificate verification to fail. I _believe_ that if it were to use the hostname that I wouldn't have to configure an SSL handler (for sync or async) and it can use the default.
