### ISSUE TITLE
java.lang.IllegalArgumentException: Infinity is not a valid double value as per JSON specification

### ISSUE THREAD

**Issue by augustobb** [searchbox-io/Jest#344]
Got this exception when running a usual bulk index request, using Jest 2.0.1:

java.lang.IllegalArgumentException: Infinity is not a valid double value as per JSON specification. To override this behavior, use Gs
onBuilder.serializeSpecialFloatingPointValues() method.
        at com.google.gson.Gson.checkValidFloatingPoint(Gson.java:317)
        at com.google.gson.Gson$3.write(Gson.java:285)
        at com.google.gson.Gson$3.write(Gson.java:271)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:112)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:239)
        at com.google.gson.internal.bind.ObjectTypeAdapter.write(ObjectTypeAdapter.java:107)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145)
        at com.google.gson.Gson.toJson(Gson.java:661)
        at com.google.gson.Gson.toJson(Gson.java:640)
        at com.google.gson.Gson.toJson(Gson.java:595)
        at com.google.gson.Gson.toJson(Gson.java:575)
        at io.searchbox.action.AbstractAction.getData(AbstractAction.java:155)
        at io.searchbox.core.Bulk.getData(Bulk.java:102)
        at io.searchbox.client.http.JestHttpClient.prepareRequest(JestHttpClient.java:81)
        at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:46)
        at io.searchbox.client.JestClient$execute.call(Unknown Source)

As pointed by the exception, if the object is a instance of double, it would be necessary to use that GsonBuilder's method

**Comment by kramer** [comment]
Code to reproduce?

**Comment by augustobb** [comment]
Hi,

the data I was dealing with has changed, and I'm currently not able to reproduce the error anymore. If it happens again I put it here.
