### ISSUE TITLE
just asking make a integration test of snapshot apis..

### ISSUE THREAD

**Issue by happyprg** [searchbox-io/Jest#369]
@kramer 
Thank you for the feedback

1.
I was wondering how can I make Integration test of snapshot & restore APIs.
once I tried but I couldn't.
because I thought that if I make Integration test, it will need FS type storage and path for save a snapshot.
is it wrong?
or... e.g) do I use Mock?
2. And What's different type between SUITE and TEST of ElasticSearchTest Annotation

thank you.

Best regards
Jeehong Lee

**Comment by kramer** [comment]
Hey @happyprg,

Sorry I forgot to reply to you earlier.

1. You could try to point fs path to a folder you would create in java temp directory, i.e.: `System.getProperty("java.io.tmpdir")`; not sure if it'll work I'd have to try it out myself. And no we don't use mocks for integration tests.
2. Please see [ESIntegTestCase JavaDocs](https://github.com/elastic/elasticsearch/blob/master/test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java#L183)

**Comment by happyprg** [comment]
Thank you for answer.
I will try it.

**Comment by happyprg** [comment]
Today, I tried to making a repository integration test for snapshot.
But, I could not register a repository information on test cluster.
Because the test cluster does not access or find out temp dir.

1. Test Code snippet
//		System.getProperty("java.io.tmpdir")  same
		File temp = File.createTempFile("testdir", "");
		temp.delete();
		temp.mkdir();

		String tmpDir = temp.getAbsolutePath();
		System.out.println("tmpDir = " + tmpDir);
		final Settings.Builder registerRepositorySettings = Settings.settingsBuilder();
		registerRepositorySettings.put("type", "fs");
		registerRepositorySettings.put("settings.compress", "true");
		registerRepositorySettings.put("settings.location", tmpDir);
		registerRepositorySettings.put("settings.chunk_size", "10m");
		registerRepositorySettings.put("settings.max_restore_bytes_per_sec", "40mb");
		registerRepositorySettings.put("settings.max_snapshot_bytes_per_sec", "40mb");
		registerRepositorySettings.put("settings.readonly", "false");


		CreateSnapshotRepository createSnapshotRepository = new CreateSnapshotRepository.Builder(REPOSITORY_NAME).settings(registerRepositorySettings.build().getAsMap()).verify(true).build();
		client.execute(createSnapshotRepository);

2. Please look at the below error msg

01:10:53 DEBUG DefaultManagedHttpClientConnection:90 - http-outgoing-0: set socket timeout to 3000
01:10:53 DEBUG MainClientExec:255 - Executing request PUT /_snapshot/leejeehong?verify=true HTTP/1.1
01:10:53 DEBUG MainClientExec:260 - Target auth state: UNCHALLENGED
01:10:53 DEBUG MainClientExec:266 - Proxy auth state: UNCHALLENGED
01:10:53 DEBUG headers:135 - http-outgoing-0 >> PUT /_snapshot/leejeehong?verify=true HTTP/1.1
01:10:53 DEBUG headers:138 - http-outgoing-0 >> Content-Length: 276
01:10:53 DEBUG headers:138 - http-outgoing-0 >> Content-Type: application/json; charset=UTF-8
01:10:53 DEBUG headers:138 - http-outgoing-0 >> Host: localhost:19300
01:10:53 DEBUG headers:138 - http-outgoing-0 >> Connection: Keep-Alive
01:10:53 DEBUG headers:138 - http-outgoing-0 >> User-Agent: Apache-HttpClient/4.5.2 (Java/1.7.0_80)
01:10:53 DEBUG headers:138 - http-outgoing-0 >> Accept-Encoding: gzip,deflate
01:10:53 DEBUG wire:72 - http-outgoing-0 >> "PUT /_snapshot/leejeehong?verify=true HTTP/1.1[\r][\n]"
01:10:53 DEBUG wire:72 - http-outgoing-0 >> "Content-Length: 276[\r][\n]"
01:10:53 DEBUG wire:72 - http-outgoing-0 >> "Content-Type: application/json; charset=UTF-8[\r][\n]"
01:10:53 DEBUG wire:72 - http-outgoing-0 >> "Host: localhost:19300[\r][\n]"
01:10:53 DEBUG wire:72 - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
01:10:53 DEBUG wire:72 - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.5.2 (Java/1.7.0_80)[\r][\n]"
01:10:53 DEBUG wire:72 - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
01:10:53 DEBUG wire:72 - http-outgoing-0 >> "[\r][\n]"
01:10:53 DEBUG wire:86 - http-outgoing-0 >> "{"settings.chunk_size":"10m","settings.compress":"true","settings.location":"C:\\Users\\jeehong\\AppData\\Local\\Temp\\testdir9114184923788276697","settings.max_restore_bytes_per_sec":"40mb","settings.max_snapshot_bytes_per_sec":"40mb","settings.readonly":"false","type":"fs"}"
01:10:53 DEBUG service:378 - [node_s0] processing [put_repository [leejeehong]]: execute
01:10:53 DEBUG repositories:396 - [node_s0] creating repository [fs][leejeehong]
01:10:53 WARN  fs:75 - [node_s0] the repository location is missing, it should point to a shared file system location that is available on all master and data nodes
01:10:53 WARN  repositories:410 - [node_s0] failed to create repository [fs][leejeehong]
org.elasticsearch.common.inject.CreationException: Guice creation errors:

1) Error injecting constructor, RepositoryException[[leejeehong] missing location]
  at org.elasticsearch.repositories.fs.FsRepository.<init>(Unknown Source)
  while locating org.elasticsearch.repositories.fs.FsRepository
  while locating org.elasticsearch.repositories.Repository

1 error
	at org.elasticsearch.common.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:360)
	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:178)
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
	at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:159)
	at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:55)
	at org.elasticsearch.repositories.RepositoriesService.createRepositoryHolder(RepositoriesService.java:404)
	at org.elasticsearch.repositories.RepositoriesService.registerRepository(RepositoriesService.java:368)
	at org.elasticsearch.repositories.RepositoriesService.access$100(RepositoriesService.java:55)
	at org.elasticsearch.repositories.RepositoriesService$1.execute(RepositoriesService.java:110)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:388)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: RepositoryException[[leejeehong] missing location]
	at org.elasticsearch.repositories.fs.FsRepository.<init>(FsRepository.java:76)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:56)
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:104)
	at org.elasticsearch.common.inject.FactoryProxy.get(FactoryProxy.java:54)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:887)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
	at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59)
	at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:46)
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:201)
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:880)
	at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
	... 13 more
01:10:53 WARN  repositories:146 - [node_s0] failed to create repository [leejeehong]
RepositoryException[[leejeehong] failed to create repository]; nested: CreationException[Guice creation errors:

1) Error injecting constructor, RepositoryException[[leejeehong] missing location]
  at org.elasticsearch.repositories.fs.FsRepository.<init>(Unknown Source)
  while locating org.elasticsearch.repositories.fs.FsRepository
  while locating org.elasticsearch.repositories.Repository

1 error]; nested: RepositoryException[[leejeehong] missing location];
	at org.elasticsearch.repositories.RepositoriesService.createRepositoryHolder(RepositoriesService.java:411)
	at org.elasticsearch.repositories.RepositoriesService.registerRepository(RepositoriesService.java:368)
	at org.elasticsearch.repositories.RepositoriesService.access$100(RepositoriesService.java:55)
	at org.elasticsearch.repositories.RepositoriesService$1.execute(RepositoriesService.java:110)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:388)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.common.inject.CreationException: Guice creation errors:

1) Error injecting constructor, RepositoryException[[leejeehong] missing location]
  at org.elasticsearch.repositories.fs.FsRepository.<init>(Unknown Source)
  while locating org.elasticsearch.repositories.fs.FsRepository
  while locating org.elasticsearch.repositories.Repository

1 error
	at org.elasticsearch.common.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:360)
	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:178)
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
	at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:159)
	at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:55)
	at org.elasticsearch.repositories.RepositoriesService.createRepositoryHolder(RepositoriesService.java:404)
	... 9 more
Caused by: RepositoryException[[leejeehong] missing location]
	at org.elasticsearch.repositories.fs.FsRepository.<init>(FsRepository.java:76)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:56)
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:104)
	at org.elasticsearch.common.inject.FactoryProxy.get(FactoryProxy.java:54)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:887)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
	at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59)
	at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:46)
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:201)
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:880)
	at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
	... 13 more
01:10:53 INFO  suppressed:131 - /_snapshot/leejeehong Params: {repository=leejeehong, verify=true}
RepositoryException[[leejeehong] failed to create repository]; nested: CreationException[Guice creation errors:

1) Error injecting constructor, RepositoryException[[leejeehong] missing location]
  at org.elasticsearch.repositories.fs.FsRepository.<init>(Unknown Source)
  while locating org.elasticsearch.repositories.fs.FsRepository
  while locating org.elasticsearch.repositories.Repository

1 error]; nested: RepositoryException[[leejeehong] missing location];
	at org.elasticsearch.repositories.RepositoriesService.createRepositoryHolder(RepositoriesService.java:411)
	at org.elasticsearch.repositories.RepositoriesService.registerRepository(RepositoriesService.java:368)
	at org.elasticsearch.repositories.RepositoriesService.access$100(RepositoriesService.java:55)
	at org.elasticsearch.repositories.RepositoriesService$1.execute(RepositoriesService.java:110)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:388)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.common.inject.CreationException: Guice creation errors:

1) Error injecting constructor, RepositoryException[[leejeehong] missing location]
  at org.elasticsearch.repositories.fs.FsRepository.<init>(Unknown Source)
  while locating org.elasticsearch.repositories.fs.FsRepository
  while locating org.elasticsearch.repositories.Repository

1 error
	at org.elasticsearch.common.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:360)
	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:178)
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
	at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:159)
	at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:55)
	at org.elasticsearch.repositories.RepositoriesService.createRepositoryHolder(RepositoriesService.java:404)
	... 9 more
Caused by: RepositoryException[[leejeehong] missing location]
	at org.elasticsearch.repositories.fs.FsRepository.<init>(FsRepository.java:76)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:56)
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:104)
	at org.elasticsearch.common.inject.FactoryProxy.get(FactoryProxy.java:54)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:887)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
	at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59)
	at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:46)
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:201)
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:880)
	at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
	... 13 more
01:10:53 DEBUG wire:72 - http-outgoing-0 << "HTTP/1.1 500 Internal Server Error[\r][\n]"
01:10:53 DEBUG wire:72 - http-outgoing-0 << "Content-Type: application/json; charset=UTF-8[\r][\n]"
01:10:53 DEBUG wire:72 - http-outgoing-0 << "Content-Length: 678[\r][\n]"
01:10:53 DEBUG wire:72 - http-outgoing-0 << "[\r][\n]"
01:10:53 DEBUG wire:86 - http-outgoing-0 << "{"error":{"root_cause":[{"type":"repository_exception","reason":"[leejeehong] failed to create repository"}],"type":"repository_exception","reason":"[leejeehong] failed to create repository","caused_by":{"type":"creation_exception","reason":"Guice creation errors:\r\n\r\n1) Error injecting constructor, RepositoryException[[leejeehong] missing location]\r\n  at org.elasticsearch.repositories.fs.FsRepository.<init>(Unknown Source)\r\n  while locating org.elasticsearch.repositories.fs.FsRepository\r\n  while locating org.elasticsearch.repositories.Repository\r\n\r\n1 error","caused_by":{"type":"repository_exception","reason":"[leejeehong] missing location"}}},"status":500}"
01:10:53 DEBUG headers:124 - http-outgoing-0 << HTTP/1.1 500 Internal Server Error
01:10:53 DEBUG headers:127 - http-outgoing-0 << Content-Type: application/json; charset=UTF-8
01:10:53 DEBUG headers:127 - http-outgoing-0 << Content-Length: 678
01:10:53 DEBUG MainClientExec:284 - Connection can be kept alive indefinitely

**Comment by ndywicki** [comment]
Hello,

I've the same issue "missing location" and lost 2h.
I followed the sample provide by the request builder test for build the map of settings : 
https://github.com/searchbox-io/Jest/blob/468d8742cf900e329093c0bb1db7e244060f0b84/jest-common/src/test/java/io/searchbox/snapshot/CreateSnapshotRepositoryTest.java#L24.

But In fact when you build settings with map like this: 
`
        Map<String, String> settings = new HashMap<>();
        settings.put("type", "fs");
        settings.put("settings.compress", "true");
        settings.put("settings.location", "backup");
`

(Or the `org.elasticsearch.common.settings.Settings.Builder`)

The payload is convert from the map to Json (with an `gson.toJson(payload)`) without the array structure  :
`        PUT _snapshot/backup
        {
            "type": "fs",
            "settings.compress": "true",
            "settings.location": "backup"
        } `

Instead of :
`PUT _snapshot/backup 
{
    "type": "fs", 
    "settings": {
        "location": "/backup",
        "compress": "true"
    }
}`

So for example you can use instead an JsonObject :
`
JsonObject payload = new JsonObject();
        payload.addProperty("type", "fs");

        // Create Inner settings JSON Object
        JsonObject settings = new JsonObject();
        settings.addProperty("compress", "true");
        settings.addProperty("location", "backup");
        payload.add("settings", settings);


        CreateSnapshotRepository createSnapshotRepository = new CreateSnapshotRepository.Builder("backup").settings(payload).build();
`

Et voila !
