### ISSUE TITLE
BulkResult throws GSon errors

### ISSUE THREAD

**Issue by simplesteph** [searchbox-io/Jest#401]
Sometimes, when running Jest, I have the following stacktrace:

```
java.lang.UnsupportedOperationException: JsonObject
    at com.google.gson.JsonElement.getAsString(JsonElement.java:191)
    at io.searchbox.core.BulkResult$BulkResultItem.<init>(BulkResult.java:98)
    at io.searchbox.core.BulkResult.getItems(BulkResult.java:36)
java.lang.UnsupportedOperationException: JsonObject
    at com.google.gson.JsonElement.getAsString(JsonElement.java:191)
    at io.searchbox.core.BulkResult$BulkResultItem.<init>(BulkResult.java:98)
    at io.searchbox.core.BulkResult.getItems(BulkResult.java:36)
```

It seems to be due to getAsString that needs to be changed to toString.
http://stackoverflow.com/questions/9324760/gson-jsonobject-unsupported-operation-exception-null-getasstring

I'm new to the library so I'm not sure how much this will impact everything, but happy to send a PR if you feel this is a minor change (one line)

**Comment by ruediste** [comment]
When I look at the code of BulkResultItem, it seems the getAsString() method is called on _id, _type and _index. Somehow one of these is parsed as JsonObject. What query did you use?

**Comment by musabgelisgen** [comment]
What do you mean by sometimes, on what condition? If you can provide the code you use, I can help you further. Closing the issue, for now, feel free to reply here.
