### ISSUE TITLE
Jest CreateIndex with settings fails on elasticsearch 5.1

### ISSUE THREAD

**Issue by arnab** [searchbox-io/Jest#468]
I ran into a problem problem trying to `CreateIndex` with `settings` with Elasticsearch 5.1. I am going to relate it to issue #461 but this looks like an independent problem.

Using the example code from the [Readme](https://github.com/searchbox-io/Jest/blob/master/jest/README.md#creating-an-index):

```java
import org.elasticsearch.common.settings.Settings;
.
.

Settings.Builder settingsBuilder = Settings.settingsBuilder();
settingsBuilder.put("number_of_shards",5);
settingsBuilder.put("number_of_replicas",1);

client.execute(new CreateIndex.Builder("articles").settings(settingsBuilder.build().getAsMap()).build());
```

* This works fine on Elasticsearch 2.3 indexes.
* On Elasticsearch 5.1 this fails with:

```
Exception in thread "main" java.io.IOException: Request POST http://localhost:9200/articles HTTP/1.1 yielded text/plain; charset=UTF-8, should be json: HTTP/1.1 400 Bad Request
	at io.searchbox.client.http.JestHttpClient.deserializeResponse(JestHttpClient.java:179)
	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:57)
...
...
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 5 path $
	at com.google.gson.JsonParser.parse(JsonParser.java:65)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at io.searchbox.action.AbstractAction.parseResponseBody(AbstractAction.java:94)
	at io.searchbox.action.AbstractAction.createNewElasticSearchResult(AbstractAction.java:65)
	at io.searchbox.action.GenericResultAbstractAction.createNewElasticSearchResult(GenericResultAbstractAction.java:20)
	at io.searchbox.client.http.JestHttpClient.deserializeResponse(JestHttpClient.java:166)
	... 12 more
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 5 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
	at com.google.gson.JsonParser.parse(JsonParser.java:60)
	... 17 more
```

This error is emitted by the error-recovery code in [JestHttpClient](https://github.com/searchbox-io/Jest/blob/master/jest/src/main/java/io/searchbox/client/http/JestHttpClient.java#L181-L190) and there are two underlying problems (found by simulating the same request with `curl`):

```
curl -XPOST 'localhost:9200/articles' -H 'Content-Type: application/json; charset=UTF-8' -d'{"settings.number_of_replicas":"1","settings.number_of_shards":"1"}'
```

* It looks like Jest makes the `CreateIndex` call as a `POST` and Elasticsearch 5.1 expects a `PUT`? This results in: `No handler found for uri [/articles] and method [POST]%`.

* If you change it to `PUT` the next issue is:

```
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"unknown setting [index.settings.number_of_replicas] did you mean [index.number_of_replicas]?"}],"type":"illegal_argument_exception","reason":"unknown setting [index.settings.number_of_replicas] did you mean [index.number_of_replicas]?"},"status":400}%
```

* So it looks like the settings need to be `{"number_of_replicas":"1","number_of_shards":"1"}` (without the `settings` prefix).

With these two changes, it works on Elasticsearch 5.1:

```
➜  ~ curl -XPUT 'localhost:9200/articles' -H 'Content-Type: application/json; charset=UTF-8' -d'{"number_of_replicas":"1","number_of_shards":"1"}'
{"acknowledged":true,"shards_acknowledged":true}%
```

**Comment by arnab** [comment]
Ah, it looks like this (the http method being subjective between `POST` and `PUT`) was changed in https://github.com/searchbox-io/Jest/commit/4de015b004e1c42203514ff35780cfb4e5c41975 - and I perhaps don't have the latest version. I'll double check.

**Comment by arnab** [comment]
After upgrading Jest, this started working for me.
