### ISSUE TITLE
NullpointerException in AbstractMultiIndexActionBuilder

### ISSUE THREAD

**Issue by akshayukey** [searchbox-io/Jest#545]
Hi,
I am getting a NullPointerException when I call Search.Builder#build() method:

`            Search search = new Search.Builder(searchSourceBuilder.toString())
.addIndex(latestIndex)
.addType("1")
.setParameter(Parameters.SIZE, size)
.setParameter(Parameters.FROM, start)
.setParameter(Parameters.EXPLAIN, debug)
.build();
`

Below is the stacktrace. The value of `indexNames` member variable in AbstractMultiIndexActionBuilder#getJoinedIndices method is not null.

`
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at com.google.common.base.Joiner.toString(Joiner.java:454)
	at com.google.common.base.Joiner.appendTo(Joiner.java:106)
	at com.google.common.base.Joiner.appendTo(Joiner.java:154)
	at com.google.common.base.Joiner.join(Joiner.java:197)
	at com.google.common.base.Joiner.join(Joiner.java:187)
	at io.searchbox.action.AbstractMultiIndexActionBuilder.getJoinedIndices(AbstractMultiIndexActionBuilder.java:47)
	at io.searchbox.action.AbstractAction.<init>(AbstractAction.java:60)
	at io.searchbox.core.Search.<init>(Search.java:34)
	at io.searchbox.core.Search$Builder.build(Search.java:257)
`

Please let me know if anyone is facing or has faced similar issue and knows how to fix it.

Thanks.

**Comment by musabgelisgen** [comment]
Can you provide the variables you pass to the methods and are you sure they are not null? I tried a similar configuration within a test and it works fine.
