### ISSUE TITLE
NodeChecker may throw NPE when close JestClient

### ISSUE THREAD

**Issue by beihaifeiwu** [searchbox-io/Jest#593]
```java
Service DataJoinService{name='ad.targaryen:v1'} has failed in the STOPPING state. java.lang.IllegalStateException: Expected the service NodeChecker [FAILED] to be TERMINATED, but the service has FAILED 
at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:344) 
at com.google.common.util.concurrent.AbstractService.awaitTerminated(AbstractService.java:307) 
at com.google.common.util.concurrent.AbstractScheduledService.awaitTerminated(AbstractScheduledService.java:425) 
at io.searchbox.client.AbstractJestClient.close(AbstractJestClient.java:83) 
at io.searchbox.client.http.JestHttpClient.close(JestHttpClient.java:109) 
at com.sample.test.DataJoinService.shutDown(DataJoinService.java:52) 
at com.google.common.util.concurrent.AbstractIdleService$DelegateService$2.run(AbstractIdleService.java:79) 
at com.google.common.util.concurrent.Callables$4.run(Callables.java:119) 
at java.lang.Thread.run(Thread.java:745) 
Caused by: java.lang.NullPointerException 
at io.searchbox.client.config.discovery.NodeChecker.runOneIteration(NodeChecker.java:100) 
at com.google.common.util.concurrent.AbstractScheduledService$ServiceDelegate$Task.run(AbstractScheduledService.java:193) 
at com.google.common.util.concurrent.Callables$4.run(Callables.java:119) 
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) 
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) 
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
... 1 more 
```

**Comment by musabgelisgen** [comment]
I assume it gave an error when it tried to access `PUBLISH_ADDRESS_KEY_V5` property of a JsonObject instance (http in this case). I fixed the problem and it should no longer throw an exception.
