### ISSUE TITLE
Could we add feature of retries in JEST ?

### ISSUE THREAD

**Issue by acoolj08** [searchbox-io/Jest#612]
Sometimes when connecting to elasticSearch I get below errors:

Caused by: org.apache.http.NoHttpResponseException: server failed to respond
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143) ~[Apache-HttpComponents-HttpClient-4.4.x.jar:?]
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57) ~[Apache-HttpComponents-HttpClient-4.4.x.jar:?]

As per my knowledge this could be handled by retrying sufficient number of times to avoid stale connection issues.

**Comment by RichardBradley** [comment]
This is already possible, using the built in retry functionality of the underlying Apache `httpclient` lib

Here is some of my code that configures 3 retries for both network failures and for 504 HTTP responses:

```
import io.searchbox.client.JestClient;
import io.searchbox.client.JestClientFactory;
import io.searchbox.client.config.HttpClientConfig;
import org.apache.http.impl.client.DefaultHttpRequestRetryHandler;
import org.apache.http.impl.client.HttpClientBuilder;

import javax.annotation.Nullable;

class MyJestClientFactory extends JestClientFactory {

    MyJestClientFactory(
            String connectionEndpoint,
            Integer maxConnectionsPerRoute) {
        HttpClientConfig.Builder httpClientConfig = new HttpClientConfig.Builder(connectionEndpoint)
                .multiThreaded(true)
                .defaultMaxTotalConnectionPerRoute(maxConnectionsPerRoute);
        setHttpClientConfig(httpClientConfig.build());
    }

    @Override
    protected HttpClientBuilder configureHttpClient(HttpClientBuilder builder) {
        builder = super.configureHttpClient(builder);

        // See DefaultHttpRequestRetryHandler.requestSentRetryEnabled
        //
        // true if it's OK to retry non-idempotent requests that have been sent
        // and then fail with network issues (not HTTP failures).
        //
        // "true" here will retry POST requests which have been sent but where
        // the response was not received. This arguably is a bit risky.
        //
        // Retries are logged at INFO level to org.apache.http.impl.execchain.RetryExec
        boolean requestSentRetryEnabled = true;

        builder.setRetryHandler(new DefaultHttpRequestRetryHandler(
                3,
                requestSentRetryEnabled));
        builder.setServiceUnavailableRetryStrategy(new GatewayTimeoutRetryStrategy());

        return builder;
    }
}

import org.apache.http.HttpResponse;
import org.apache.http.client.ServiceUnavailableRetryStrategy;
import org.apache.http.protocol.HttpContext;
import org.apache.http.util.Args;


// Based on org.apache.http.impl.client.DefaultServiceUnavailableRetryStrategy, but retries on 504s rather than 503s.
public class GatewayTimeoutRetryStrategy implements ServiceUnavailableRetryStrategy {
    private final int maxRetries;
    private final long retryInterval;

    public GatewayTimeoutRetryStrategy(int maxRetries, int retryInterval) {
        Args.positive(maxRetries, "Max retries");
        Args.positive(retryInterval, "Retry interval");
        this.maxRetries = maxRetries;
        this.retryInterval = (long)retryInterval;
    }

    public GatewayTimeoutRetryStrategy() {
        this(1, 1000);
    }

    @Override
    public boolean retryRequest(HttpResponse response, int executionCount, HttpContext context) {
        return executionCount <= this.maxRetries && response.getStatusLine().getStatusCode() == 504;
    }

    @Override
    public long getRetryInterval() {
        return this.retryInterval;
    }
}
```
