### ISSUE TITLE
The getTotal() method of the SearchResult class reports an UnsupportedOperationException error when used

### ISSUE THREAD

**Issue by wuchunfu** [searchbox-io/Jest#656]
I now have a problem running my program when I use the `getTotal()` method. Here is the `API` used by my program: 

```java
SearchResult result = client.execute(search);
Long total = result.getTotal();
```

The following is the `Json` data returned by the `result.getJsonObject()` method:

```java
{
    "took":166,
    "timed_out":false,
    "_shards":{
        "total":1,
        "successful":1,
        "skipped":0,
        "failed":0
    },
    "hits":{
        "total":{
            "value":96,
            "relation":"eq"
        },
        "max_score":268.59442,
        "hits":[
            Object{...},
            Object{...}
        ]
    }
}
```

The following is the error message: 

```java
java.lang.UnsupportedOperationException: JsonObject
	at com.google.gson.JsonElement.getAsLong(JsonElement.java:231) ~[gson-2.8.5.jar:na]
	at io.searchbox.core.SearchResult.getTotal(SearchResult.java:218) ~[jest-common-6.3.1.jar:na]
```

Similar problems arise when I try to use other methods in the `SearchResult` class. If this is a `BUG`, I hope to fix this problem as soon as possible. If this is not a `BUG`, I hope to give a solution.

**Current version: **

`jest-6.3.1`

**Expected results: **

I hope I can use the methods in the `SearchResult` class properly, or give other solutions.

**Comment by 760374564** [comment]
Here is my solution. 
Create a new **JestResult** implementation which extends **SearchResult** and override mehtods **getTotal()** and **getMaxScore()**. 
Like this:
`// fix jest issues: "https://github.com/searchbox-io/Jest/issues/656"
public class ISearchResult extends SearchResult {

	public ISearchResult(SearchResult searchResult) {
		super(searchResult);
	}

	@Override
	public Long getTotal() {
		Long total = null;
		JsonObject obj = (JsonObject) getPath(PATH_TO_TOTAL);
		if (obj != null)
			total = obj.getAsJsonPrimitive("value").getAsLong();
		return total;
	}

	@Override
	public Float getMaxScore() {
		Float maxScore = null;
		JsonObject obj = (JsonObject) getPath(PATH_TO_MAX_SCORE);
		if (obj != null && !obj.isJsonNull())
			maxScore = obj.getAsJsonPrimitive("value").getAsFloat();
		return maxScore;
	}
}`

Here's the usage：
`SearchResult searchResult = new ISearchResult(jestClient.execute(//query string...));
			if (searchResult.isSucceeded()) {
				 //if succeeded
			} else {
				 //if failed
			}`
Hope it works for you. Good luck!

**Comment by wuchunfu** [comment]
Thank you for your reply. I will try to solve the problem according to the information you provided.

**Comment by zylzhangyilin** [comment]
I have the same problem.      
line 31 : public static final String[] PATH_TO_TOTAL = "hits/total".split("/"); 
the PATH_TO_TOTAL returns a json element like this : {"value":180,"relation":"eq"}
the path maybe "hits/total/value".split("/");

**Comment by zylzhangyilin** [comment]
I solved it with the flowing method
```java
public static long getTotal(JestResult jestResult) {
        if (jestResult.isSucceeded()) {
            String[] path = "hits/total/value".split("/");
            JsonObject jsonObject = jestResult.getJsonObject();
            if (jsonObject != null) {
                JsonElement obj = jsonObject;
                String[] var4 = path;
                int var5 = path.length;

                for (int var6 = 0; var6 < var5; ++var6) {
                    String component = var4[var6];
                    if (obj == null) {
                        break;
                    }

                    obj = ((JsonObject) obj).get(component);
                }
                if (Objects.nonNull(obj)) {
                    return obj.getAsLong();
                } else {
                    return 0L;
                }
            } else {
                return 0L;
            }
        } else {
            throw new RuntimeException("查询失败");
        }
    }
```
